# Site settings
title: Mike Spencer - JavaScript | HTML | CSS
email: mikespencema@gmail.com
description: > # Mike Spencer - JavaScript | HTML | CSS
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mikespencer.github.io" # the base hostname & protocol for your site
twitter_username: mikeaspencer
github_username:  mikespencer

# Build settings
markdown: kramdown
